version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_DB=medium
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    networks:
      - backend
networks:
  backend:
